// Datos iniciales del Universo de Prospectos (lcg.xlsx — Universo y Pipeline).
// Se insertan automáticamente cuando la tabla universo está vacía.
export const UNIVERSO_SEED = [
  { empresa: 'Morelia / Michoacán', rubro: 'Público', segmento: 'Gob.', contacto_nombre: 'Jaime Verduzco', telefono: '4436120238', tipo: 'Gobierno estatal', responsable: 'Alonso', fecha_contacto: '2026-05-12', status_contacto: 'Primera reunión', etapa_pipeline: 'Reunión agendada' },
  { empresa: 'Centauros del Sureste', rubro: 'Carga terrestre · Sureste · Paquetería', segmento: 'Privado', telefono: '55-5552-3122', sitio_web: 'centaurosdelsureste.com' },
  { empresa: 'Transportes SIVI', rubro: 'Logística · Distribución · Aduana AICM', segmento: 'Privado', sitio_web: 'transportesivi.com' },
  { empresa: 'Control Terrestre', rubro: 'FTL · Transfronterizo · Carga especializada', segmento: 'Privado', sitio_web: 'controlterrestre.com' },
  { empresa: 'TRACMEX / Transportes de Carga de México', rubro: 'Logística · Distribución · Materiales peligrosos', segmento: 'Privado', sitio_web: 'tracmex.com.mx' },
  { empresa: 'Transportes Calderón', rubro: 'Carga general · Sobredimensionada · Materiales peligrosos', segmento: 'Privado', sitio_web: 'transportescalderon.com.mx' },
  { empresa: "Transportes Quinta's", rubro: 'Carga general · Fletes · Distribución CDMX', segmento: 'Privado', sitio_web: 'transportesquintas.com' },
  { empresa: 'Transportes Rapicuates', rubro: "Carga nacional · Caja seca 48'", segmento: 'Privado', sitio_web: 'transportesrapicuates.com' },
  { empresa: 'TGB Fletes', rubro: 'Fletes CDMX y Edomex · Caja seca · Plataforma', segmento: 'Privado', sitio_web: 'tgbfletes.mx' },
  { empresa: 'Transportes Esquivel', rubro: "Carga general · Caja seca 53' · Logística industrial", segmento: 'Privado', sitio_web: 'transportesesquivel.com.mx' },
  { empresa: 'Red TL', rubro: 'Carga 3.5 ton · Distribución zona metro', segmento: 'Privado', sitio_web: 'redtl.com.mx' },
  { empresa: 'Transportes de Carga García', rubro: 'Carga general · FTL · LTL · Materiales peligrosos · HazMat', segmento: 'Privado', sitio_web: 'transportedecargagarcia.com' },
  { empresa: 'Transportes Raquel', rubro: 'Carga terrestre · Logística · Nacional', segmento: 'Privado', sitio_web: 'transportesraquel.com.mx' },
  { empresa: 'DNUSMIR Transportes', rubro: 'Carga general · Maquinaria · Aduana · Plataformas', segmento: 'Privado', sitio_web: 'transportesdnusmir.com' },
  { empresa: 'Transportes de Carga (45 años Tlalnepantla)', rubro: 'Carga nacional · 45 años · Parque vehicular propio', segmento: 'Privado', sitio_web: 'transportesdecarga.com.mx' },
  { empresa: 'Traxión (Div. CDMX)', rubro: 'Carga · Personal · Mudanzas · Logística integral', segmento: 'Privado' },
  { empresa: 'Transportes Rapicuates (corredor norte)', rubro: 'Carga nacional · Caja seca · Corredor norte', segmento: 'Privado', sitio_web: 'transportesrapicuates.com' },
  { empresa: 'Transportes AS', rubro: 'Logística y transporte de carga', segmento: 'Privado', sitio_web: 'https://transportes-as.com' },
  { empresa: 'Transporte Logístico en Querétaro', rubro: 'Transporte y logística', segmento: 'Privado' },
  { empresa: 'Bajío Logistics', rubro: 'Transporte de carga (Bajío)', segmento: 'Privado' },
  { empresa: 'Transportes LOGORO SA de CV', rubro: 'Transporte de carga terrestre', segmento: 'Privado' },
  { empresa: 'Transportes Grupo Beltrán', rubro: 'Transporte de carga terrestre', segmento: 'Privado' },
  { empresa: 'TLM FLETES', rubro: 'Transporte y logística terrestre', segmento: 'Privado' },
  { empresa: 'Transpormer SA de CV', rubro: 'Transporte de carga', segmento: 'Privado' },
  { empresa: 'Transportes Rendon', rubro: 'Transporte de carga federal', segmento: 'Privado' },
  { empresa: 'Kuehne + Nagel México (Querétaro)', rubro: 'Operador logístico', segmento: 'Privado' },
  { empresa: 'Xpress Logistics (Querétaro)', rubro: 'Transporte y distribución', segmento: 'Privado' },
  { empresa: 'Transportes de Personal Gutiérrez SA de CV', rubro: 'Transporte de personal', segmento: 'Privado' },
  { empresa: 'Transportadora García', rubro: 'Transporte de carga', segmento: 'Privado' },
  { empresa: 'Transportes Queretanos Flecha Azul SA de CV', rubro: 'Transporte de carga', segmento: 'Privado' },
  { empresa: 'Transportes Empresarial del Bajío', rubro: 'Transporte de personal', segmento: 'Privado' },
  { empresa: 'TEAM Larranaga (Transportes Industriales del Bajío)', rubro: 'Transporte de carga industrial', segmento: 'Privado' },
  { empresa: 'TLB (Transportación y Logística del Bajío)', rubro: 'Carga ligera y porteo', segmento: 'Privado' },
  { empresa: 'Direct Drive Logistics (Guanajuato)', rubro: 'Transporte FTL/LTL', segmento: 'Privado' },
  { empresa: 'Transportes GAR-VEN SA de CV', rubro: 'Transporte de personal y carga', segmento: 'Privado' },
  { empresa: 'TL Transporte de Personal', rubro: 'Transporte de personal corporativo', segmento: 'Privado' },
  { empresa: 'XPL Servicios', rubro: 'Operador logístico', segmento: 'Privado' },
  { empresa: 'Conexiones Logísticas CLI', rubro: 'Logística y transporte', segmento: 'Privado' },
  { empresa: 'Roal Transportes', rubro: 'Transporte de carga', segmento: 'Privado' },
  { empresa: 'Tracargo', rubro: 'Transporte y logística', segmento: 'Privado' },
  { empresa: 'Vinpac Fedemex Querétaro', rubro: 'Logística y transporte', segmento: 'Privado' },
  { empresa: 'Transportes Queretanos', rubro: 'Transporte de carga y personal', segmento: 'Privado' },
  { empresa: 'Transportes de Personal Gutiérrez', rubro: 'Transporte de personal', segmento: 'Privado' },
  { empresa: 'Open Warehouse (Bajío)', rubro: 'Operador logístico', segmento: 'Privado' },
  { empresa: 'Transportes Grúas y Montajes Navarro', rubro: 'Transporte especializado con grúas', segmento: 'Privado' },
  { empresa: 'Voyager Transportes', rubro: 'Transporte en SLP', segmento: 'Privado' },
  { empresa: 'Oriental San Luis Potosí', rubro: 'Transporte y logística', segmento: 'Privado' },
  { empresa: 'Transportadora García (SLP)', rubro: 'Logística y transporte', segmento: 'Privado' },
  { empresa: 'Operadores Logísticos en Querétaro (DirectoriOcarga)', rubro: 'Logística y transporte', segmento: 'Privado' },
  { empresa: 'Transporte Empresarial del Bajío (TEB)', rubro: 'Transporte de personal', segmento: 'Privado' },
  { empresa: 'Direct Drive Logistics', rubro: 'Transporte FTL/LTL', segmento: 'Privado' },
  { empresa: 'Tresguerras', rubro: 'Transporte de carga general y paquetería', segmento: 'Privado' },
  { empresa: 'TEB / Transporte Empresarial del Bajío', rubro: 'Personal industrial / Parques industriales', segmento: 'Privado' },
  { empresa: 'TIBSA / Transportes Industriales del Bajío', rubro: 'Carga general / Paquetería regional', segmento: 'Privado' },
  { empresa: 'Silja Logistics', rubro: 'Automotriz / Maquila Bajío', segmento: 'Privado' },
  { empresa: 'TLB / Transportación y Logística del Bajío', rubro: 'Carga general regional', segmento: 'Privado' },
  { empresa: 'Transportes NIU', rubro: 'Automotriz / Textil / Maquila', segmento: 'Privado' },
  { empresa: 'ROAL Transportes', rubro: 'Automotriz / Metalmecánica ruta Qro-Monterrey', segmento: 'Privado' },
  { empresa: 'Transportes Rendón', rubro: 'Carga nacional / 20+ destinos', segmento: 'Privado' },
  { empresa: 'Transportes SANJI', rubro: 'Carga general nacional', segmento: 'Privado' },
  { empresa: 'Grupo Transhers', rubro: 'Carga general / Rastreo satelital', segmento: 'Privado' },
  { empresa: 'Fletes Frías Express (FFESA)', rubro: 'Carga terrestre seca y refrigerada', segmento: 'Privado' },
  { empresa: 'Transportes Fleterán', rubro: 'Carga seca y refrigerada', segmento: 'Privado' },
  { empresa: 'Apro Logistics', rubro: 'Transporte terrestre nacional', segmento: 'Privado' },
  { empresa: 'RITREMA Transportes', rubro: 'Personal / Parques industriales Bajío', segmento: 'Privado' },
  { empresa: 'CT Transporta / Corporativo Transporta', rubro: 'Personal + carga / App WIGO', segmento: 'Privado' },
  { empresa: 'Grupo Caronte Soluciones Logísticas', rubro: 'Carga general nacional', segmento: 'Privado' },
  { empresa: 'MyM Express', rubro: 'Automotriz / Carga industrial', segmento: 'Privado' },
  { empresa: 'Garven Transportes', rubro: 'Carga general / Personal', segmento: 'Privado' },
  { empresa: 'Transportes Ramos', rubro: 'Carga local y foránea', segmento: 'Privado' },
  { empresa: 'Transportes Valdez García', rubro: 'Carga general foránea', segmento: 'Privado' },
]
